@echo off
echo Fixing Android Gradle Plugin version compatibility...
echo.

echo Step 1: Backing up current gradle files...
copy android\build.gradle android\build.gradle.backup 2>nul
copy android\gradle\wrapper\gradle-wrapper.properties android\gradle\wrapper\gradle-wrapper.properties.backup 2>nul
echo.

echo Step 2: Updating Android Gradle Plugin to compatible version...
echo # This file was generated by the Gradle 'init' task. > android\gradle.properties
echo. >> android\gradle.properties
echo # For more details on how to configure your build environment visit >> android\gradle.properties
echo # http://www.gradle.org/docs/current/userguide/build_environment.html >> android\gradle.properties
echo. >> android\gradle.properties
echo # Specifies the JVM arguments used for the daemon process. >> android\gradle.properties
echo # The setting is particularly useful for tweaking memory settings. >> android\gradle.properties
echo # Default value: -Xmx1024m -XX:MaxPermSize=256m >> android\gradle.properties
echo org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m >> android\gradle.properties
echo. >> android\gradle.properties
echo # When configured, Gradle will run in incubating parallel mode. >> android\gradle.properties
echo # This option should only be used with decoupled projects. More details, visit >> android\gradle.properties
echo # http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects >> android\gradle.properties
echo org.gradle.parallel=true >> android\gradle.properties
echo. >> android\gradle.properties
echo # AndroidX package structure to make it clearer which packages are bundled with the >> android\gradle.properties
echo # Android operating system, and which are packaged with your app's APK >> android\gradle.properties
echo # https://developer.android.com/topic/libraries/support-library/androidx-rn >> android\gradle.properties
echo android.useAndroidX=true >> android\gradle.properties
echo # Automatically convert third-party libraries to use AndroidX >> android\gradle.properties
echo android.enableJetifier=true >> android\gradle.properties
echo. >> android\gradle.properties
echo # Use this property to specify which architecture you want to build. >> android\gradle.properties
echo # You can also override it from the CLI using >> android\gradle.properties
echo # ./gradlew -PReactNativeArchitectures=x86_64 >> android\gradle.properties
echo ReactNativeArchitectures=armeabi-v7a,arm64-v8a >> android\gradle.properties
echo. >> android\gradle.properties
echo # Use this property to enable support to the new architecture. >> android\gradle.properties
echo # This will allow you to use TurboModules and the Fabric render in >> android\gradle.properties
echo # your application. You should enable this flag either if you want >> android\gradle.properties
echo # to write custom TurboModules/Fabric components OR use libraries that >> android\gradle.properties
echo # are providing them. >> android\gradle.properties
echo newArchEnabled=false >> android\gradle.properties
echo. >> android\gradle.properties
echo # Use this property to enable or disable the Hermes JS engine. >> android\gradle.properties
echo # If set to false, you will be using JSC instead. >> android\gradle.properties
echo hermesEnabled=true >> android\gradle.properties
echo.

echo Step 3: Updating Gradle Wrapper to compatible version...
echo distributionBase=GRADLE_USER_HOME > android\gradle\wrapper\gradle-wrapper.properties
echo distributionPath=wrapper/dists >> android\gradle\wrapper\gradle-wrapper.properties
echo distributionUrl=https\://services.gradle.org/distributions/gradle-8.10-all.zip >> android\gradle\wrapper\gradle-wrapper.properties
echo networkTimeout=10000 >> android\gradle\wrapper\gradle-wrapper.properties
echo validateDistributionUrl=true >> android\gradle\wrapper\gradle-wrapper.properties
echo zipStoreBase=GRADLE_USER_HOME >> android\gradle\wrapper\gradle-wrapper.properties
echo zipStorePath=wrapper/dists >> android\gradle\wrapper\gradle-wrapper.properties
echo.

echo Step 4: Cleaning build cache...
cd android
call gradlew clean
cd ..
echo.

echo AGP version fix completed!
echo The project should now use compatible versions:
echo - Gradle: 8.10
echo - Android Gradle Plugin: 8.10.0 (will be set by Expo)
echo - New Architecture: Disabled
echo.
pause
